### ISSUE TITLE
Google Maps - Not working in production 

### ISSUE THREAD

**Issue by AllanBallester** [LeaWoittequand/Spores#58]
<img width="1344" alt="capture d ecran 2017-12-22 a 19 14 52" src="https://user-images.githubusercontent.com/17672429/34308214-7b069a58-e74c-11e7-9e10-6e6dedc61ef6.png">

**Comment by LeaWoittequand** [comment]
@AllanBallester Ca marche chez moi :/
En inspectant tu as quoi comme erreur dans la console ? 
Par contre prob de CSS sur la page des flats, je regarde et je résous ça !!

**Comment by AllanBallester** [comment]
@LeaWoittequand Check with your phone and another computer.
If it still doesn't work we know that it should come from gmap in production.
Let's check that when you have time . Neck kisses

**Comment by LeaWoittequand** [comment]
@AllanBallester 
It's working !! 
MAC, PC, IPHONE : ✔✔✔

**Comment by AllanBallester** [comment]
<img width="703" alt="capture d ecran 2018-02-10 a 20 07 23" src="https://user-images.githubusercontent.com/17672429/36065664-221da228-0e9e-11e8-80a5-abf1cfa6882e.png">
